import Foundation
import AppKit
import CoreGraphics

/// Passive session event tap used only to detect human interference. Events
/// generated by Input carry Input.marker and are ignored here.
final class InputMonitor: @unchecked Sendable {
    static let shared = InputMonitor()
    private var tap: CFMachPort?
    private var source: CFRunLoopSource?
    private(set) var active = false
    private(set) var failure: String?
    private var lastMove: CGPoint = .zero
    private var moveAt = Date.distantPast
    private var moved = CGFloat.zero

    private init() {}

    func start() {
        guard tap == nil else { return }
        let events: CGEventMask = [
            CGEventType.mouseMoved, .leftMouseDown, .rightMouseDown,
            .otherMouseDown, .scrollWheel, .keyDown, .flagsChanged
        ].reduce(0) { $0 | (CGEventMask(1) << CGEventMask($1.rawValue)) }
        let info = Unmanaged.passUnretained(self).toOpaque()
        guard let created = CGEvent.tapCreate(tap: .cgSessionEventTap,
                                              place: .headInsertEventTap,
                                              options: .listenOnly,
                                              eventsOfInterest: events,
                                              callback: InputMonitor.callback,
                                              userInfo: info) else {
            failure = "Input monitoring unavailable: grant Input Monitoring or Accessibility in System Settings"
            active = false
            return
        }
        tap = created
        source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, created, 0)
        if let source {
            CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
            CGEvent.tapEnable(tap: created, enable: true)
            active = true
            failure = nil
        }
    }

    func stop() {
        if let tap { CGEvent.tapEnable(tap: tap, enable: false) }
        if let source { CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes) }
        tap = nil
        source = nil
        active = false
    }

    private func observe(_ event: CGEvent, type: CGEventType) {
        if event.getIntegerValueField(.eventSourceUserData) == Input.marker { return }
        if type == .mouseMoved {
            let point = event.location
            let now = Date()
            if now.timeIntervalSince(moveAt) > 0.1 {
                moved = 0
                lastMove = point
                moveAt = now
            } else {
                moved += hypot(point.x - lastMove.x, point.y - lastMove.y)
                lastMove = point
            }
            if moved < 4 { return }
        }
        Task {
            if await ActionGate.shared.interrupt() {
                await MainActor.run { VisualFeedbackController.shared.pause(byHumanInput: true) }
            }
        }
    }

    private static let callback: CGEventTapCallBack = { _, type, event, userInfo in
        if let userInfo {
            Unmanaged<InputMonitor>.fromOpaque(userInfo).takeUnretainedValue().observe(event, type: type)
        }
        return Unmanaged.passUnretained(event)
    }
}
