package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/Tutitoos/atenea/internal/wrap"
)

// cmdCompatOverlay emits the ephemeral overlay generated by the same wrap
// renderers used by the normal client launcher. It intentionally has no
// settings or network input: the core entry is enough for the compatibility
// gate, and keeping this output machine-readable avoids shell placeholders.
func cmdCompatOverlay(args []string, out io.Writer) error {
	flags := flag.NewFlagSet("compat-overlay", flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	client := flags.String("client", "", "client overlay to render")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *client == "" || flags.NArg() != 0 {
		return fmt.Errorf("compat-overlay requires --client codex|claude|opencode")
	}
	self, err := os.Executable()
	if err != nil {
		return fmt.Errorf("locate atenea executable: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(self); err == nil {
		self = resolved
	}
	if self, err = filepath.Abs(self); err != nil {
		return fmt.Errorf("make atenea executable path absolute: %w", err)
	}
	overlay, err := (wrap.Plan{}).ClientOverlay(*client, wrap.Core{ID: "atenea", Command: []string{self, "mcp"}})
	if err != nil {
		return err
	}
	return json.NewEncoder(out).Encode(overlay)
}
